# Get Inputs

In [178]:
#Independent variables
import random
import numpy as np
input_set = np.array([[0,1,0],
                      [0,0,1],
                      [1,0,0],
                      [1,1,0],
                      [1,1,1],
                      [0,1,1],
                      [0,1,0]])#Dependent variable
labels = np.array([[1,
                    0,
                    0,
                    1,
                    1,
                    0,
                    1]])
labels = labels.reshape(7,1) #to convert labels to vector

# Get Parameters

In [179]:
#Define Hyperparameters
#considering no fractions
np.random.seed(42)
weights = np.round(np.random.rand(3,1) *100)
bias= np.round(np.random.rand(1)*100)
lr = [5,100] #learning rate
print(type(lr))

<class 'list'>


In [180]:
weights = np.zeros((3,2))
np.random.seed(10)
for i in range(3):
    weights[i][0] = np.round(np.random.rand(1)*100)
    weights[i][1] = 100
bias = np.zeros(2)
bias[0] = np.round(np.random.rand(1)*100)
bias[1] = 100 
print(weights)
print(bias)               

[[ 77. 100.]
 [  2. 100.]
 [ 63. 100.]]
[ 75. 100.]


In [181]:
# #multiplying inputs with weights in matrices 
# def addfrac(a,b,c,d,e,f):
#     num = a*d*f + c*b*f+e*b*d
#     den = b*d*f
#     return num,den

In [182]:
#define activation function
# def sigmoid(x):
#     return 1/(1+np.exp(-x))

# Define Sigmoid Function

In [183]:
# taylor series works when x<1
# Assumption based on values of x
# need to check the bwlow formulas of taylor series one more time
def sigmoidfrac(x,y):
    if(x/y>=10):
        num = 1; den = 1
    elif((x/y)>=9 and (x/y)<10):
        num = 99988; den = 100000
    elif((x/y)>=8 and (x/y)<9):
        num = 99966; den = 100000
    elif((x/y)>=7 and (x/y)<8):
        num = 99909; den = 100000
    elif((x/y)>=6 and (x/y)<7):
        num = 99753; den = 100000
    elif((x/y)>=5 and (x/y)<6):
        num = 99331; den = 100000
    elif((x/y)>=1 and (x/y)<5):
        q = int(x/y) 
        r = x%y
        num= pow(19,q)*24*pow(y,4)
        den= pow(19,q)*24*pow(y,4)+pow(7,q)*(24*pow(y,4)-24*r*pow(y,3)+12*pow(r,2)*pow(y,2)-4*y*pow(r,3)+pow(r,4))    
    elif(x/y>-1 and x/y<1):
        num= 24*pow(y,4)
        den= 48*pow(y,4)-24*x*pow(y,3)+12*pow(x,2)*pow(y,2)-4*y*pow(x,3)+pow(x,4)   
    elif(x/y>-6 and x/y<=-1):
        q = int(x/y) 
        r = x%y
        num = 24*pow(y,4)*pow(7,-q)
        den = 24*pow(y,4)*pow(7,-q)+pow(19,-q)*(24*pow(y,4)+24*r*pow(y,3)+12*pow(r,2)*pow(y,2)+4*y*pow(r,3)+pow(r,4))
    elif(x/y>-7 and x/y<=-6):
        num =15; den= 10000 
    elif(x/y>-8 and x/y<=-7):
        num =6; den = 10000     
    elif(x/y>-9 and x/y<=-8):
        num =2; den = 10000 
    elif(x/y>-10 and x/y<=-9):
         num = 7; den = 100000
    elif(x/y<=-10):
         num =0 ; den =1
    return num,den

In [184]:
# Python Program to find the L.C.M. of two input number
def compute_lcm(x, y):
   # choose the greater number
   if x > y:
       greater = x
   else:
       greater = y
   while(True):
       if((greater % x == 0) and (greater % y == 0)):
           lcm = greater
           break
       greater += 1
   return lcm

In [185]:
# define derivative
def sigmoid_derivative(x,y):
    num = x*y-pow(x,2)
    den = pow(y,2)
    return num,den

In [186]:
#adding num and den version of the form a/b and c/d
def addition(a,b,c,d):
    den = compute_lcm(b,d)
    num = ((den/b)*a) + ((den/d)*c)
#     print(num,den)
    return float(num),float(den)
        

In [187]:
def multiply_xwb(x,y,bn,bd):
    t = np.zeros((7,2))
    for i in range(x.shape[0]):
        t1 = (x[i][0]*y[0][0])
        t2 = y[0][1]
        t3 = (x[i][1]*y[1][0])
        t4 = y[1][1]
        t1,t2 = addition(t1,t2,t3,t4)
        t3 = (x[i][2]*y[2][0])
        t4 = y[2][1]
        t1,t2 = addition(t1,t2,t3,t4)
        num,den = addition(t1,t2,bn,bd)
        t[i][0]= float(num)
        t[i][1]= float(den)
    return t

In [188]:
def subtraction(a,b,c,d):
    den = compute_lcm(b,d)
#     print("lcm is ",den)
    num = ((den/b)*a) - ((den/d)*c)
    return num,den

In [189]:
def multiply(a,b,c,d): # of the form a/b * c/d
    num = a*c
    den = b*d
    return num,den

In [190]:
import math
def arraylcm(a):
  lcm = a[0]
  for i in range(1,len(a)):
    lcm = lcm*a[i]//math.gcd(lcm, a[i])
  return lcm

In [191]:
def mul_e_sd_i(x,y):
    for i in range(x.shape[0]):
        t1 = (x[i][0]*y[0][0])
        t2 = y[0][1]
        t3 = (x[i][1]*y[1][0])
        t4 = y[1][1]
        t1,t2 = addition(t1,t2,t3,t4)
        t3 = (x[i][2]*y[2][0])
        t4 = y[2][1]
        t1,t2 = addition(t1,t2,t3,t4)
        num,den = addition(t1,t2,bn,bd)
        

# Multiply weights with Inputs and add bias

In [192]:
#Multiply inputs into weights.
XW = multiply_xwb(input_set,weights,bias[0],bias[1])
# print(XW)

In [193]:
# print("printing dot product",XW)

In [194]:
# define derivative
# def sigmoid_derivative(x):
#     return (x*(100-x))

# Get Sigmoid outputs for XW

In [195]:
# #get sigmoid derivative
# z = sigmoidfrac(XW)  #sigmoid activation function
def get_sigmoid(x):
    z=np.zeros((7,2))
    for i in range(x.shape[0]):
        a,b = sigmoidfrac(x[i][0],x[i][1])
        z[i][0] = int(str(a)[:3]) 
        z[i][1] = int(str(b)[:3])
    return z 
z = get_sigmoid(XW)
print(z)


[[240. 351.]
 [456. 570.]
 [456. 555.]
 [456. 553.]
 [866. 965.]
 [456. 568.]
 [240. 351.]]


# Calculating cost/error

In [196]:
def cost(a,b):
    c = np.zeros((7,2))
    for i in range (a.shape[0]):
        num,den = subtraction(a[i][0],a[i][1],b[i],1,)
        c[i][0] = num
        c[i][1] = den
    return c
error = cost(z,labels)
print(error)

[[-111.  351.]
 [ 456.  570.]
 [ 456.  555.]
 [ -97.  553.]
 [ -99.  965.]
 [ 456.  568.]
 [-111.  351.]]


# Get derivative of SD_Input

In [198]:
def get_SD(a):
    b=np.zeros((7,2))
    for i in range(a.shape[0]):
        num,den = sigmoidfrac(a[i][0],a[i][1])
        b[i][0] = int(str(num)[:3]) 
        b[i][1] = int(str(den)[:3])
    c = np.zeros((7,2))
    for i in range(7):
        x,y = sigmoid_derivative(b[i][0], b[i][1])
        c[i][0] =x
        c[i][1] =y
    return c
SD = get_SD(z)
print("sigmoid derivative is ",SD)

sigmoid derivative is  [[ 66976. 300304.]
 [ 28842. 134689.]
 [ 22927. 107584.]
 [ 22176. 104329.]
 [ 17680.  85849.]
 [ 28137. 131044.]
 [ 66976. 300304.]]


# Calculate error multiplied to SD 

In [147]:
# get error multiplied to SD
def get_exsd(a,b):
    c = np.zeros((7,2))
    for i in range(len(a)):
        num = a[i][0]*b[i][0]
        den = a[i][1]*b[i][1]
        c[i][0] = num 
        c[i][1] = den
    d = np.zeros((7,2))
    for i in range(len(a)):
        d[i][0] = int((c[i][0]/c[i][1])*10000)
        d[i][1] = 10000
    return d
res = get_exsd(error,SD)
print(res)


[[ -705. 10000.]
 [ 1713. 10000.]
 [ 1750. 10000.]
 [ -372. 10000.]
 [ -211. 10000.]
 [ 1723. 10000.]
 [ -705. 10000.]]


# Calculate error * SD * Inputs *lr

In [149]:
def get_exsdxi(input_set,res,l):
    inputs = input_set.T
    b = np.zeros((3,2))
    num = 0
    den = 0
    for j in range(inputs.shape[0]):
        for i in range(res.shape[0]):
            num = num+ inputs[j][i]*res[i][0]*l[0]
            den = res[0][1]*l[1] 
        b[j][0] = num 
        b[j][1] = den 
        num=0
        den=0
    return b
inp_res = get_exsdxi(input_set,res,lr)
print(inp_res)

[[   5835. 1000000.]
 [  -1350. 1000000.]
 [  16125. 1000000.]]


# Get New Weights and Bias

In [150]:
# Get new Weights
# for i in range(len(weights)):
#     num,den = subtraction(weights[i][0], weights[i][1], inp_res[i][0],inp_res[i][1])
#     weights[i][0]= num
#     weights[i][1] =den
# weights

def get_new_weight(a,b):
    c = np.zeros((3,2))
    for i in range(len(a)):
        num,den = subtraction(a[i][0], a[i][1], b[i][0],b[i][1])
        c[i][0]= num
        c[i][1] =den
    return c
weights = get_new_weight(weights,inp_res)
print(weights)

[[ 764165. 1000000.]
 [  21350. 1000000.]
 [ 613875. 1000000.]]


In [151]:
#compute lr * l_res
def get_new_bias(b,r,l):
    bn= np.zeros((7,2))
    for i in range(res.shape[0]):
        r[i][0] =  r[i][0]*l[0]
        r[i][1] =  r[i][1]*l[1]
        bn[i][0] = int(r[i][0]/r[i][1] *10000)
        bn[i][1] = 10000
        num,den = subtraction(b[0],b[1], bn[i][0],bn[i][1])
        b[0] = num
        b[1] = den
    return b

bias = get_new_bias(bias,res,lr)
print(bias)

[ 7340. 10000.]


In [144]:
# train ANN model and this accumulation of earlier step
for epoch in range(10):
    inputs = input_set  # set aside the original input
    XW = np.dot(inputs, weights)+ bias  # dot product of input and add bias
    #     print("printing dot product",XW)
#     z = sigmoid(XW)  #sigmoid activation function
    z=np.zeros([7,1])
    for i in range(7):
        a = sigmoidfrac(XW[i])
        z[i] = a
    print ("sigmoid output is:",z )
    print ("sigmoid output is:",z )
    error = z - labels  #backprop step1
    print ("error is ",error)
    print("error sum is",error.sum())   #backpro step 2
    dcost = error
    dpred = sigmoid_derivative(z)
    print("sigmoid derivative is ",dpred)
    z_del = dcost * dpred
    inputs = input_set.T
    weights = weights - lr*np.dot(inputs, z_del)
    
    for num in z_del:
        bias = bias - lr*num

In [145]:
print(inputs.shape)
print(weights.shape)


(3, 7)
(3, 2)


# Perform Prediction

In [146]:

single_pt = np.array([30,20,10])
input1 = np.dot(single_pt, weights) + bias
print(single_pt.shape)
print(input1.shape)
print(weights.shape)
print(input1)
# num,den = sigmoidfrac()
# print(num,den)

(3,)
(2,)
(3, 2)
[29187187. 60010000.]


In [147]:
single_pt = np.array([30,30,20])
num1,den1 = sigmoidfrac(input1[0])
num2,den2 = sigmoidfrac(input1[1])

print(num1,den1)
print(num2,den2)

TypeError: sigmoidfrac() missing 1 required positional argument: 'y'

In [148]:
single_pt = np.array([30,30,20])
num,den = sigmoidfrac(np.dot(single_pt, weights) + bias)
print(num,den)

TypeError: sigmoidfrac() missing 1 required positional argument: 'y'