# Get Inputs

In [18]:
#Independent variables
import numpy as np

input_set = np.array([[10,20,10],
                      [10,10,20],
                      [20,15,15],
                      [25,25,15],
                      [24,24,28],
                      [12,22,20],
                      [8,18,10]])#Dependent variable
labels = np.array([[20,
                    10,
                    10,
                    20,
                    20,
                    10,
                    20]])    # no need to scale, need original label
labels = labels.reshape(7,1) #to convert labels to vector

# Get Parameters

In [19]:
#Define Hyperparameters
np.random.seed(42)
weights = np.round(np.random.rand(3,1) *100)
bias = np.round(np.random.rand(1) * 100)
lr = 5 #learning rate
print(weights)
print(bias)
print(lr)

[[37.]
 [95.]
 [73.]]
[60.]
5


In [20]:
#define activation function
# def sigmoid(x):
#     return 1/(1+np.exp(-x))

# Define Sigmoid Function

In [21]:
# taylor series works when x<1
def sigmoidfrac(x):
    num = 24*pow(x,4)+ 24*pow(x,3)+12*pow(x,2)+8*x+1
    den = 48*pow(x,4)+ 24*pow(x,3)+12*pow(x,2)+8*x+1        
    return num,den
#     if(x>17):
#         num =0
#         den =1
#     else:
#         num = 24*pow(x,4)+ 24*pow(x,3)+12*pow(x,2)+8*x+1
#         den = 48*pow(x,4)+ 24*pow(x,3)+12*pow(x,2)+8*x+1
        
#     return num,den

In [22]:
#define derivative
# def sigmoid_derivative(x):
#     return sigmoidfrac(x)*(1-sigmoidfrac(x))

# Multiply weights with Inputs and add bias

In [23]:
#multiply inputs
inputs = input_set  # set aside the original input
XW = np.dot(inputs, weights)+ bias  # dot product of input and add bias
print("printing dot product",XW)

printing dot product [[3060.]
 [2840.]
 [3320.]
 [4455.]
 [5272.]
 [4054.]
 [2796.]]


In [24]:
#define derivative
# def sigmoid_derivative(x):
#     return sigmoidfrac(x)*(1-sigmoidfrac(x))

# Get Sigmoid outputs

In [25]:
#get sigmoid derivative
#z = sigmoidfrac(XW)  #sigmoid activation function
z=np.zeros([7,2])

for i in range(7):
    a,b = sigmoidfrac(XW[i])
    z[i][0] = a
    z[i][1] = b
print ("sigmoid output is:",z )

#sigmoid output in the form of 2d array for numerator and denominator

sigmoid output is: [[2.10493589e+15 4.20918401e+15]
 [1.56184353e+15 3.12313721e+15]
 [2.91671764e+15 5.83255688e+15]
 [9.45582791e+15 1.89095335e+16]
 [1.85436502e+16 3.70837833e+16]
 [6.48415438e+15 1.29667095e+16]
 [1.46728757e+15 2.93405044e+15]]


# Calculating cost/error

In [26]:

error = z - labels  #backprop step1
print ("error is ",error)
print("error sum is",error.sum())   #backpro step 2

#labels are too small and subtraction is not making sense at all as the numerator and denominator numbers are very big

error is  [[2.10493589e+15 4.20918401e+15]
 [1.56184353e+15 3.12313721e+15]
 [2.91671764e+15 5.83255688e+15]
 [9.45582791e+15 1.89095335e+16]
 [1.85436502e+16 3.70837833e+16]
 [6.48415438e+15 1.29667095e+16]
 [1.46728757e+15 2.93405044e+15]]
error sum is 1.2759337199342773e+17


In [27]:
# dpred = np.zeros([7,2])
# for i in range(len(dpred)):
#     dpred[i][0] = z[i][0] * (1 - )

# Get derivative

In [28]:
#calculate derivative
dpred = np.zeros([7,2])
dcost = error
for i in range(7):
    dpred[i][0] = (z[i][0] * z[i][1]) - pow(z[i][0],2)
    dpred[i][1] = pow(z[i][1],2)
print("sigmoid derivative is ",dpred)

sigmoid derivative is  [[4.42930740e+30 1.77172301e+31]
 [2.43849643e+30 9.75398603e+30]
 [8.50467975e+30 3.40187198e+31]
 [8.93926136e+31 3.57570459e+32]
 [3.43801743e+32 1.37520698e+33]
 [4.20338883e+31 1.68135556e+32]
 [2.15216293e+30 8.60865200e+30]]


In [29]:
#Calculate new weight
#slope = input*dcost*dpred
SL1 = dcost * dpred
print(SL1)


[[9.32340812e+45 7.45750815e+46]
 [3.80854987e+45 3.04630367e+46]
 [2.48057494e+46 1.98416118e+47]
 [8.45281171e+47 6.76149059e+48]
 [6.37533924e+48 5.09978777e+49]
 [2.72554221e+47 2.18016491e+48]
 [3.15784191e+45 2.52582192e+46]]


# Get New Weights

In [30]:
inputs = input_set.T
weights = weights - lr*np.dot(inputs, SL1)
    
for num in SL1:
    bias = bias - lr*num
print(bias)
print(weights)

#weights are ending up being negative, need to discuss resolution on this.

[-3.76713509e+49 -3.01341228e+50]
[[-8.90317595e+50 -7.12184539e+51]
 [-9.03949225e+50 -7.23088490e+51]
 [-9.86064353e+50 -7.88775034e+51]]


In [31]:
#train ANN model and this accumulation of earlier step
# for epoch in range(10):
#     inputs = input_set  # set aside the original input
#     XW = np.dot(inputs, weights)+ bias  # dot product of input and add bias
#     print("printing dot product",XW)
#     z = sigmoid(XW)  #sigmoid activation function
#     print ("sigmoid output is:",z )
#     error = z - labels  #backprop step1
#     print ("error is ",error)
#     print("error sum is",error.sum())   #backpro step 2
#     dcost = error
#     dpred = sigmoid_derivative(z)
#     print("sigmoid derivative is ",dpred)
#     z_del = dcost * dpred
#     inputs = input_set.T
#     weights = weights - lr*np.dot(inputs, z_del)
    
#     for num in z_del:
#         bias = bias - lr*num

In [32]:
print(inputs.shape)
print(weights.shape)


(3, 7)
(3, 2)


# Perform Prediction

In [33]:

single_pt = np.array([30,20,10])
input1 = np.dot(single_pt, weights) + bias
print(single_pt.shape)
print(input1.shape)
print(weights.shape)
print(input1)
# num,den = sigmoidfrac()
# print(num,den)

(3,)
(2,)
(3, 2)
[-5.46868272e+52 -4.37451904e+53]


In [34]:
single_pt = np.array([30,30,20])
num,den = sigmoidfrac(np.dot(single_pt, weights) + bias)
print(num,den)

[7.0374409e+212 2.8814108e+216] [1.40748818e+213 5.76282160e+216]
