# Get Inputs

In [1]:
#Independent variables
import numpy as np

input_set = np.array([[10,20,10],
                      [10,10,20],
                      [20,15,15],
                      [25,25,15],
                      [24,24,28],
                      [12,22,20],
                      [8,18,10]])#Dependent variable
labels = np.array([[20,
                    10,
                    10,
                    20,
                    20,
                    10,
                    20]])    # no need to scale, need original label
labels = labels.reshape(7,1) #to convert labels to vector

# Get Parameters

In [2]:
#Define Hyperparameters
np.random.seed(42)
weights = np.round(np.random.rand(3,1) *100)
bias = np.round(np.random.rand(1) * 100)
lr = 5 #learning rate
print(weights)
print(bias)
print(lr)
# weight need to have numerator and denominator

[[37.]
 [95.]
 [73.]]
[60.]
5


In [3]:
#define activation function
# def sigmoid(x):
#     return 1/(1+np.exp(-x))

# Define Sigmoid Function

In [4]:
# taylor series works when |x| <1
def sigmoidfrac(x):
#     num = 24*pow(x,4)+ 24*pow(x,3)+12*pow(x,2)+8*x+1
#     den = 48*pow(x,4)+ 24*pow(x,3)+12*pow(x,2)+8*x+1        
#     return num,den
    if(x>=10):
        num =1
        den =1
    elif(): #...till x = 1
        num = 99999
        den = 100000
    elif(x>5 ) # continue till 0 then -1
    
    elif(x<-12):
        num = 0
        den = 1
    else:
        num = 24*pow(x,4)+ 24*pow(x,3)+12*pow(x,2)+8*x+1
        den = 48*pow(x,4)+ 24*pow(x,3)+12*pow(x,2)+8*x+1
        
    return num,den



In [5]:
#define derivative
# def sigmoid_derivative(x):
#     return sigmoidfrac(x)*(1-sigmoidfrac(x))

# Multiply weights with Inputs and add bias

In [6]:
#multiply inputs
inputs = input_set  # set aside the original input
XW = np.dot(inputs, weights)+ bias  # dot product of input and add bias
print("printing dot product",XW)

printing dot product [[3060.]
 [2840.]
 [3320.]
 [4455.]
 [5272.]
 [4054.]
 [2796.]]


In [7]:
#define derivative
# def sigmoid_derivative(x):
#     return sigmoidfrac(x)*(1-sigmoidfrac(x))

# Get Sigmoid outputs

In [8]:
#get sigmoid derivative
#z = sigmoidfrac(XW)  #sigmoid activation function
z=np.zeros([7,2])

for i in range(7):
    a,b = sigmoidfrac(XW[i])
    z[i][0] = a
    z[i][1] = b
print ("sigmoid output is:",z )

#sigmoid output in the form of 2d array for numerator and denominator

sigmoid output is: [[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


# Calculating cost/error

In [9]:

error = z - labels  #backprop step1
print ("error is ",error)
print("error sum is",error.sum())   #backpro step 2

#labels are too small and subtraction is not making sense at all as the numerator and denominator numbers are very big

error is  [[-20. -19.]
 [-10.  -9.]
 [-10.  -9.]
 [-20. -19.]
 [-20. -19.]
 [-10.  -9.]
 [-20. -19.]]
error sum is -213.0


In [10]:
# dpred = np.zeros([7,2])
# for i in range(len(dpred)):
#     dpred[i][0] = z[i][0] * (1 - )

# Get derivative

In [11]:
#calculate derivative
dpred = np.zeros([7,2])
dcost = error
dpred - sigmoid
print("sigmoid derivative is ",dpred)

sigmoid derivative is  [[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [12]:
#Calculate new weight
#slope = input*dcost*dpred
SL1 = dcost * dpred
print(SL1)


[[ -0. -19.]
 [ -0.  -9.]
 [ -0.  -9.]
 [ -0. -19.]
 [ -0. -19.]
 [ -0.  -9.]
 [ -0. -19.]]


# Get New Weights

In [13]:
inputs = input_set.T
weights = weights - lr*np.dot(inputs, SL1)
    
for num in SL1:
    bias = bias - lr*num
print(bias)
print(weights)

#weights are ending up being negative, need to discuss resolution on this.

[ 60. 575.]
[[   37.  8292.]
 [   95. 10475.]
 [   73.  8533.]]


In [14]:
#train ANN model and this accumulation of earlier step
# for epoch in range(10):
#     inputs = input_set  # set aside the original input
#     XW = np.dot(inputs, weights)+ bias  # dot product of input and add bias
#     print("printing dot product",XW)
#     z = sigmoid(XW)  #sigmoid activation function
#     print ("sigmoid output is:",z )
#     error = z - labels  #backprop step1
#     print ("error is ",error)
#     print("error sum is",error.sum())   #backpro step 2
#     dcost = error
#     dpred = sigmoid_derivative(z)
#     print("sigmoid derivative is ",dpred)
#     z_del = dcost * dpred
#     inputs = input_set.T
#     weights = weights - lr*np.dot(inputs, z_del)
    
#     for num in z_del:
#         bias = bias - lr*num

In [15]:
print(inputs.shape)
print(weights.shape)


(3, 7)
(3, 2)


# Perform Prediction

In [16]:

single_pt = np.array([30,20,10])
input1 = np.dot(single_pt, weights) + bias
print(single_pt.shape)
print(input1.shape)
print(weights.shape)
print(input1)
# num,den = sigmoidfrac()
# print(num,den)

(3,)
(2,)
(3, 2)
[  3800. 544165.]


In [19]:
single_pt = np.array([30,30,20])
num1,den1 = sigmoidfrac(input1[0])
num2,den2 = sigmoidfrac(input1[1])

print(num1,den1)
print(num2,den2)

0 1
0 1


In [ ]:
single_pt = np.array([30,30,20])
num,den = sigmoidfrac(np.dot(single_pt, weights) + bias)
print(num,den)