# Get Inputs

In [29]:
#Independent variables
import random
import numpy as np
input_set = np.array([[0,1,0],
                      [0,0,1],
                      [1,0,0],
                      [1,1,0],
                      [1,1,1],
                      [0,1,1],
                      [0,1,0]])#Dependent variable
labels = np.array([[1,
                    0,
                    0,
                    1,
                    1,
                    0,
                    1]])
labels = labels.reshape(7,1) #to convert labels to vector

# Get Parameters

In [30]:
#Define Hyperparameters
#considering no fractions
np.random.seed(42)
weights = np.round(np.random.rand(3,1) *100)
bias= np.round(np.random.rand(1)*100)
lr = [5,100] #learning rate
print(type(lr))

<class 'list'>


In [31]:
weights = np.zeros((3,2))
np.random.seed(10)
for i in range(3):
    weights[i][0] = np.round(np.random.rand(1)*100)
    weights[i][1] = 100
bias = np.zeros(2)
bias[0] = np.round(np.random.rand(1)*100)
bias[1] = 100 
print(weights)
print(bias)               

[[ 77. 100.]
 [  2. 100.]
 [ 63. 100.]]
[ 75. 100.]


In [32]:
# #multiplying inputs with weights in matrices 
# def addfrac(a,b,c,d,e,f):
#     num = a*d*f + c*b*f+e*b*d
#     den = b*d*f
#     return num,den

In [33]:
#define activation function
# def sigmoid(x):
#     return 1/(1+np.exp(-x))

# Define Sigmoid Function

In [34]:
# taylor series works when x<1
# Assumption based on values of x
# need to check the bwlow formulas of taylor series one more time
def sigmoidfrac(x,y):
    if(x/y>=10):
        num = 1; den = 1
    elif((x/y)>=9 and (x/y)<10):
        num = 99988; den = 100000
    elif((x/y)>=8 and (x/y)<9):
        num = 99966; den = 100000
    elif((x/y)>=7 and (x/y)<8):
        num = 99909; den = 100000
    elif((x/y)>=6 and (x/y)<7):
        num = 99753; den = 100000
    elif((x/y)>=5 and (x/y)<6):
        num = 99331; den = 100000
    elif((x/y)>=1 and (x/y)<5):
        q = int(x/y) 
        r = x%y
        num= pow(19,q)*24*pow(y,4)
        den= pow(19,q)*24*pow(y,4)+pow(7,q)*(24*pow(y,4)-24*r*pow(y,3)+12*pow(r,2)*pow(y,2)-4*y*pow(r,3)+pow(r,4))    
    elif(x/y>-1 and x/y<1):
        num= 24*pow(y,4)
        den= 48*pow(y,4)-24*x*pow(y,3)+12*pow(x,2)*pow(y,2)-4*y*pow(x,3)+pow(x,4)   
    elif(x/y>-6 and x/y<=-1):
        q = int(x/y) 
        r = x%y
        num = 24*pow(y,4)*pow(7,-q)
        den = 24*pow(y,4)*pow(7,-q)+pow(19,-q)*(24*pow(y,4)+24*r*pow(y,3)+12*pow(r,2)*pow(y,2)+4*y*pow(r,3)+pow(r,4))
    elif(x/y>-7 and x/y<=-6):
        num =15; den= 10000 
    elif(x/y>-8 and x/y<=-7):
        num =6; den = 10000     
    elif(x/y>-9 and x/y<=-8):
        num =2; den = 10000 
    elif(x/y>-10 and x/y<=-9):
         num = 7; den = 100000
    elif(x/y<=-10):
         num =0 ; den =1
    return num,den

In [35]:
# Python Program to find the L.C.M. of two input number
def compute_lcm(x, y):
   # choose the greater number
   if x > y:
       greater = x
   else:
       greater = y
   while(True):
       if((greater % x == 0) and (greater % y == 0)):
           lcm = greater
           break
       greater += 1
   return lcm

In [36]:
# define derivative
def sigmoid_derivative(x,y):
    num = x*y-pow(x,2)
    den = pow(y,2)
    return num,den

In [37]:
#adding num and den version of the form a/b and c/d
def addition(a,b,c,d):
    den = compute_lcm(b,d)
    num = ((den/b)*a) + ((den/d)*c)
#     print(num,den)
    return float(num),float(den)
        

In [38]:
def multiply_xwb(x,y,bn,bd):
    t = np.zeros((7,2))
    for i in range(x.shape[0]):
        t1 = (x[i][0]*y[0][0])
        t2 = y[0][1]
        t3 = (x[i][1]*y[1][0])
        t4 = y[1][1]
        t1,t2 = addition(t1,t2,t3,t4)
        t3 = (x[i][2]*y[2][0])
        t4 = y[2][1]
        t1,t2 = addition(t1,t2,t3,t4)
        num,den = addition(t1,t2,bn,bd)
        t[i][0]= float(num)
        t[i][1]= float(den)
    return t

In [39]:
def subtraction(a,b,c,d):
    den = compute_lcm(b,d)
#     print("lcm is ",den)
    num = ((den/b)*a) - ((den/d)*c)
    return num,den

In [40]:
def multiply(a,b,c,d): # of the form a/b * c/d
    num = a*c
    den = b*d
    return num,den

In [41]:
import math
def arraylcm(a):
  lcm = a[0]
  for i in range(1,len(a)):
    lcm = lcm*a[i]//math.gcd(lcm, a[i])
  return lcm

In [42]:
def mul_e_sd_i(x,y):
    for i in range(x.shape[0]):
        t1 = (x[i][0]*y[0][0])
        t2 = y[0][1]
        t3 = (x[i][1]*y[1][0])
        t4 = y[1][1]
        t1,t2 = addition(t1,t2,t3,t4)
        t3 = (x[i][2]*y[2][0])
        t4 = y[2][1]
        t1,t2 = addition(t1,t2,t3,t4)
        num,den = addition(t1,t2,bn,bd)
        

# Multiply weights with Inputs and add bias

In [43]:
#Multiply inputs into weights.
XW = multiply_xwb(input_set,weights,bias[0],bias[1])
# print(XW)

In [44]:
# print("printing dot product",XW)

In [45]:
# define derivative
# def sigmoid_derivative(x):
#     return (x*(100-x))

# Get Sigmoid outputs for XW

In [55]:
# #get sigmoid derivative
# z = sigmoidfrac(XW)  #sigmoid activation function
def get_sigmoid(x):
    z=np.zeros((7,2))
    for i in range(x.shape[0]):
        a,b = sigmoidfrac(x[i][0],x[i][1])
#         z[i][0] = int(str(a)[:3]) 
#         z[i][1] = int(str(b)[:3])
        z[i][0] = a
        z[i][1] = b
    return z 
z = get_sigmoid(XW)
print(z)


[[2.40000000e+25 3.53199042e+25]
 [4.56000000e+26 5.74646179e+26]
 [4.56000000e+26 5.58123929e+26]
 [4.56000000e+26 5.55976618e+26]
 [8.66400000e+27 9.69314591e+27]
 [4.56000000e+26 5.72142382e+26]
 [2.40000000e+25 3.53199042e+25]]


# Calculating cost/error

In [56]:
def cost(a,b):
    c = np.zeros((7,2))
    for i in range (a.shape[0]):
        num,den = subtraction(a[i][0],a[i][1],b[i],1,)
        c[i][0] = num
        c[i][1] = den
    return c
error = cost(z,labels)
print(error)

[[-1.13199042e+25  3.53199042e+25]
 [ 4.56000000e+26  5.74646179e+26]
 [ 4.56000000e+26  5.58123929e+26]
 [-9.99766183e+25  5.55976618e+26]
 [-1.02914591e+27  9.69314591e+27]
 [ 4.56000000e+26  5.72142382e+26]
 [-1.13199042e+25  3.53199042e+25]]


# Get derivative of XW

In [58]:
def get_SD(a):
    b=np.zeros((7,2))
    for i in range(a.shape[0]):
        num,den = sigmoidfrac(a[i][0],a[i][1])
#         b[i][0] = int(str(num)[:3]) 
#         b[i][1] = int(str(den)[:3])
        b[i][0] = num 
        b[i][1] = den
    c = np.zeros((7,2))
    for i in range(7):
        x,y = sigmoid_derivative(b[i][0], b[i][1])
        c[i][0] =x
        c[i][1] =y
    return c
SD = get_SD(z)
print("sigmoid derivative is ",SD)

sigmoid derivative is  [[7.08599220e+206 3.17214648e+207]
 [3.11324873e+216 1.44906347e+217]
 [2.41018689e+216 1.13148331e+217]
 [2.32994222e+216 1.09508627e+217]
 [1.85488000e+226 8.96512866e+226]
 [2.99633130e+216 1.39639805e+217]
 [7.08599220e+206 3.17214648e+207]]


# Calculate error multiplied to SD multiplied to inputs

In [59]:
# get error multiplied to SD
def get_exsd(a,b):
    c = np.zeros((7,2))
    for i in range(len(a)):
        num = a[i][0]*b[i][0]
        den = a[i][1]*b[i][1]
        c[i][0] = num 
        c[i][1] = den
    d = np.zeros((7,2))
    for i in range(len(a)):
        d[i][0] = int((c[i][0]/c[i][1])*10000)
        d[i][1] = 10000
    return d
res = get_exsd(error,SD)
print(res)


[[ -715. 10000.]
 [ 1704. 10000.]
 [ 1740. 10000.]
 [ -382. 10000.]
 [ -219. 10000.]
 [ 1710. 10000.]
 [ -715. 10000.]]


In [60]:
#get error multiplied to SD, multiplied to Inputs

In [66]:
def get_exsdxi(input_set,res,l):
    inputs = input_set.T
    b = np.zeros((3,2))
    num = 0
    den = 0
    for j in range(inputs.shape[0]):
        for i in range(res.shape[0]):
            num = num+ inputs[j][i]*res[i][0]*l[0]
            den = res[0][1]*l[1] 
        b[j][0] = num 
        b[j][1] = den 
        num=0
        den=0
    return b
inp_res = get_exsdxi(input_set,res,lr)
print(inp_res)

[[ 2.8475e+04  1.0000e+08]
 [-8.0250e+03  1.0000e+08]
 [ 7.9875e+04  1.0000e+08]]


# Get New Weights and Bias

In [62]:
# Get new Weights
# for i in range(len(weights)):
#     num,den = subtraction(weights[i][0], weights[i][1], inp_res[i][0],inp_res[i][1])
#     weights[i][0]= num
#     weights[i][1] =den
# weights

def get_new_weight(a,b):
    c = np.zeros((3,2))
    for i in range(len(a)):
        num,den = subtraction(a[i][0], a[i][1], b[i][0],b[i][1])
        c[i][0]= num
        c[i][1] =den
    return c
weights = get_new_weight(weights,inp_res)
print(weights)

[[ 758470. 1000000.]
 [  22955. 1000000.]
 [ 597900. 1000000.]]


In [63]:
#compute lr * l_res
def get_new_bias(b,r,l):
    bn= np.zeros((7,2))
    for i in range(res.shape[0]):
        r[i][0] =  r[i][0]*l[0]
        r[i][1] =  r[i][1]*l[1]
        bn[i][0] = int(r[i][0]/r[i][1] *10000)
        bn[i][1] = 10000
        num,den = subtraction(b[0],b[1], bn[i][0],bn[i][1])
        b[0] = num
        b[1] = den
    return b

bias = get_new_bias(bias,res,lr)
print(bias)

[ 7182. 10000.]


In [73]:
# train ANN model and this accumulation of earlier step
for epoch in range(25000):
    inputs = input_set  # set aside the original input
    XW =  multiply_xwb(inputs,weights,bias[0],bias[1]) # dot product of input and add bias
    z=get_sigmoid(XW)    #getting sigmoid outputs
#     print ("sigmoid output is:",z ) 
    error = cost(z,labels)  #calculate cost
#     print ("error is ",error)
    dcost = error
    dpred = get_SD(z) # getting sigmoid derivative
#     print("sigmoid derivative is ",dpred)
    z_del = get_exsd(dcost,dpred)  # multiply error and sigmoid derivative
#     inputs = input_set.T
#     print(inputs)
    comp_A  = get_exsdxi(inputs,z_del,lr)  #multiply error* sd *inputs * lerarning rate
    weights = get_new_weight(weights,comp_A)
    bias = get_new_bias(bias,z_del,lr)

In [74]:
print(weights)
print(bias)


[[ 6563455.  1000000.]
 [14166925.  1000000.]
 [-7465685.  1000000.]]
[-97043.  10000.]


In [84]:
print(pt.shape[0])
print(weights.shape)
print(pt[0])

3
(3, 2)
1


# Perform Prediction

In [91]:
pt = np.array([1,0,0])
num = 0
for i in range(pt.shape[0]):
    num = num + pt[i]*weights[i][0] 
    den = weights[0][1]
    x = addition(num,den,bias[0],bias[1])
    pred= sigmoidfrac(x[0],x[1])
    pred = (pred[0]/pred[1])
print(pred_fin)

0.020778919877495916


In [92]:
pt = np.array([0,1,0])
num = 0
for i in range(pt.shape[0]):
    num = num + pt[i]*weights[i][0] 
    den = weights[0][1]
    x = addition(num,den,bias[0],bias[1])
    pred  = sigmoidfrac(x[0],x[1])
    pred = (pred[0]/pred[1])
print(pred)

0.9885299558146738


In [93]:
single_pt = np.array([0,1,0])
num = 0
for i in range(pt.shape[0]):
    num = num + pt[i]*weights[i][0] 
    den = weights[0][1]
    x = addition(num,den,bias[0],bias[1])
    pred  = sigmoidfrac(x[0],x[1])
    pred = (pred[0]/pred[1])
print(pred)

0.9885299558146738
